In [1]:
# If you use Colab Notebook, you can uncomment the following to mount your Google Drive to Colab
# After that, your colab notebook can read/write files and data in your colab

#from google.colab import drive
#drive.mount('/content/drive')



In [2]:
# If you use Colab Notebook, please change the current directory to be the folder that you save 
# your Notebook and data folder for example, I save my Colab files and data at the following location

#%cd /content/drive/MyDrive/Colab\ Notebooks

In [3]:
# call libraries that will be used
import numpy as np      # Low-level numerical Python library. https://numpy.org/

## Scalars, Vectors, and Matrices

### Scalars

In [4]:
# define a scalar
x = np.array(0.5)

x

array(0.5)

### Vectors

In [5]:
# define a row vector
x = np.array([1., 3., 4.])

x

array([1., 3., 4.])

In [6]:
# define a colum vector
x = np.array([[1.],
     [3.],
     [4.]])

x

array([[1.],
       [3.],
       [4.]])

### Matrices

In [7]:
# define a single row matrix and then reshape it
A = np.arange(1.,7.).reshape(3,2)

# alternatively
A=np.matrix('[1.,2.,3.;4.,5.,6.]')

A


matrix([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
# define a matrix by delineating element by element

A = np.arange(1.,7.).reshape(2,3)

# alternatively
A = np.matrix('[1.,2.;3.,4.;5.,6.]')

A

matrix([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [9]:
# define a matrix by delineating row by row
A = np.matrix([[1., 2.],
              [3., 4.],
              [5., 6.]])

A

matrix([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [10]:
# define matrix by reshaping a vector
A = np.arange(1.,13.).reshape(2,3,2)

A


array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]])

## Operations

### Transpose

In [11]:
A = np.arange(1.,7.).reshape(2,3)
print('A:\n', A,'\n')

A_T = np.transpose(A) # np.transpose()
print('The transpose of A, A^T:\n', A_T,'\n')

A:
 [[1. 2. 3.]
 [4. 5. 6.]] 

The transpose of A, A^T:
 [[1. 4.]
 [2. 5.]
 [3. 6.]] 



### Addition & Subtraction

In [12]:
A = np.arange(1.,7.).reshape(3,2)
print('A=\n', A, '\n')

B = np.arange(7.,13.).reshape(3,2)
print('B=\n', B, '\n')

d= np.arange(10.,13.).reshape(3,1)
print('d=\n',d,'\n')

print('A+B=\n', A+B,'\n')

print('2*A+3=\n', 2*A+3,'\n')

print('A+d=\n',A+d,'\n')

print('A-B=\n', A-B,'\n')



A=
 [[1. 2.]
 [3. 4.]
 [5. 6.]] 

B=
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]] 

d=
 [[10.]
 [11.]
 [12.]] 

A+B=
 [[ 8. 10.]
 [12. 14.]
 [16. 18.]] 

2*A+3=
 [[ 5.  7.]
 [ 9. 11.]
 [13. 15.]] 

A+d=
 [[11. 12.]
 [14. 15.]
 [17. 18.]] 

A-B=
 [[-6. -6.]
 [-6. -6.]
 [-6. -6.]] 



### Multiplication

In [13]:
A = np.arange(1.,7.).reshape(3,2)
print('A=\n', A, '\n')

B = np.arange(7.,13.).reshape(3,2)
print('B=\n', B, '\n')

c = np.arange(4.,6.)
print('c=\n', c, '\n')

d = np.arange(1.,4.)
print('d=\n', d, '\n')

E = np.arange(1.,7.).reshape(2,3)
print('E=\n', E, '\n')

# Hadamard product (element-wise product)
print('A*B=\n', A*B, '\n')

# matrix multiplication (using np.matmul)
print('dA=\n', np.matmul(d,A), '\n')

print('EA=\n', np.matmul(E,A), '\n')

print('Ac^T=\n', np.matmul(A,np.transpose(c)),'\n')

A=
 [[1. 2.]
 [3. 4.]
 [5. 6.]] 

B=
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]] 

c=
 [4. 5.] 

d=
 [1. 2. 3.] 

E=
 [[1. 2. 3.]
 [4. 5. 6.]] 

A*B=
 [[ 7. 16.]
 [27. 40.]
 [55. 72.]] 

dA=
 [22. 28.] 

EA=
 [[22. 28.]
 [49. 64.]] 

Ac^T=
 [14. 32. 50.] 



### Matrix Diagonal

In [14]:
A = np.arange(1.,17.).reshape(4,4)
print('A=\n',A, '\n')

A_diag=np.diag(A) # find the diagnal of the matrix using np.diag()
print('Diagonal values of A:\n', A_diag)

A=
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]] 

Diagonal values of A:
 [ 1.  6. 11. 16.]


### Matrix Transpose

In [15]:
A = np.arange(1.,7.).reshape(2,3)
print('A:\n',A,'\n')

A_T=np.transpose(A)
print('The transpose of A, A_T:\n',A_T,'\n')

A:
 [[1. 2. 3.]
 [4. 5. 6.]] 

The transpose of A, A_T:
 [[1. 4.]
 [2. 5.]
 [3. 6.]] 



### Identity Matrix and Inverse Operator

In [16]:
a = np.arange(2.,5.)
print('a:\n', a,'\n')

I = np.eye(3)
print('I:\n', I,'\n')

print('aI:\n',np.matmul(a,I),'\n') # check if aI does not change the vector a

print('Ia:\n', np.matmul(I,np.transpose(a))) # check if Ia^T does not change a

a:
 [2. 3. 4.] 

I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

aI:
 [2. 3. 4.] 

Ia:
 [2. 3. 4.]


In [17]:
# Inverse of a matrix
A = np.arange(1.,5.).reshape(2,2)
print('A:\n', A, '\n')

A_inv=np.linalg.inv(A) # find the inverse of a matrix using np.linalg.inv
print('The inverse of A:\n', A_inv,'\n')

print('A multiplied by its inverse matrix, AA_inv, is the identify matrix:\n', np.matmul(A,A_inv),'\n') # the multiplication of A and A's inverse is an identical matrix


A:
 [[1. 2.]
 [3. 4.]] 

The inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]] 

A multiplied by its inverse matrix, AA_inv, is the identify matrix:
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]] 



### Trace

In [18]:
A = np.arange(1.,10.).reshape(3,3)
print('A:\n', A, '\n')

A_trace = np.trace(A) # np.trace() is the function for finding the trace of a matrix
print('The trace of A: \n', A_trace) # check if A_trace is the summation of elements on the diagnal

A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

The trace of A: 
 15.0


### Determinant

In [19]:
A=np.arange(1.,5.).reshape(2,2)
print('A:\n', A, '\n')

A_det=np.linalg.det(A) # find the determinant of a matrix using np.linalg.det
print('determinant of A:\n', "%.2f" % A_det)

A:
 [[1. 2.]
 [3. 4.]] 

determinant of A:
 -2.00


## Norms

### $l_1$-Norm

In [20]:
A=np.arange(-2.,2.)
print('A:\n', A,'\n')

A_norm1=np.linalg.norm(A,ord=1) #np.linalg.norm(tensor, ord=) computes the norm of a tensor
print('L_1 norm of A:\n',"%.2f"% A_norm1)

A:
 [-2. -1.  0.  1.] 

L_1 norm of A:
 4.00


### $l_2$-Norm

In [21]:
A=np.arange(-2.,2.)
print('A:\n', A,'\n')

A_norm2=np.linalg.norm(A,ord=2)
print('L_2 norm of A:\n', "%.2f" % A_norm2)

A:
 [-2. -1.  0.  1.] 

L_2 norm of A:
 2.45


### $l_\infty$-Norm

In [22]:
A=np.arange(-2.,2.)
print('A:\n', A,'\n')

A_norminf=np.linalg.norm(A,ord=np.inf)
print('L_inf norm of A:\n', "%.2f" % A_norminf)

A:
 [-2. -1.  0.  1.] 

L_inf norm of A:
 2.00


### Frobenius Norm

In [23]:
A=np.arange(-2.,2.).reshape(2,2)
print('A:\n', A,'\n')

A_Fro=np.linalg.norm(A,ord='fro')
print('Frobenius norm of A:\n', "%.2f" % A_Fro)

A:
 [[-2. -1.]
 [ 0.  1.]] 

Frobenius norm of A:
 2.45


## Decompositions

### Eigen Decomposition

In [24]:
A = np.array([5.,1.,3.,3.]).reshape(2,2)
print('A:\n', A,'\n')

e,V=np.linalg.eig(A)# find eigenvalues and eigenvectors of a matrix using np.linalg.eig()
print('eigenvalues of A:\n e=', e,'\n')

print('eigenvectors of A: \n V=', V,'\n')

L=(np.diag(e)) #construct the eighen value matrix using np.diag()
print('Eigenvalue matrix:\n', L, '\n')

print('EigenDecomposition of A:\n', abs(np.matmul(np.matmul(V,L),np.linalg.inv(V)))-A,'\n') # check if A is equal to its eigendecomposition VLV^(-1)


print('det(A)-the product of eigenvalues:\n', np.linalg.det(A)-np.prod(e),'\n') # check if the determinant of A is equal to the product of A's eigenvalues


A:
 [[5. 1.]
 [3. 3.]] 

eigenvalues of A:
 e= [6. 2.] 

eigenvectors of A: 
 V= [[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]] 

Eigenvalue matrix:
 [[6. 0.]
 [0. 2.]] 

EigenDecomposition of A:
 [[-1.77635684e-15  4.44089210e-16]
 [-4.44089210e-16  4.44089210e-16]] 

det(A)-the product of eigenvalues:
 -3.552713678800501e-15 



### Singular Value Decomposition

In [25]:
A = np.random.randn(2,3)
print('A:\n',A,'\n')

U,D,V = np.linalg.svd(A, full_matrices=False) # singular value decomposition using np.linalg.svd()
print('left singular vectors, U:\n', U,'\n')
print('singular values, D:\n', D,'\n')
print('right singular vectors, V:\n', V,'\n')

np.transpose(V)
#np.matmul(np.matmul(U,np.diag(D)),np.transpose(V))

print('UDV-A:\n', np.matmul(np.matmul(U,np.diag(D)), V)-A) # let's check if UDV is approximately equal to A

A:
 [[ 0.21098848  0.0430892   1.09352414]
 [-0.51639576  2.72043294 -1.89301755]] 

left singular vectors, U:
 [[-0.19416184 -0.98096951]
 [ 0.98096951 -0.19416184]] 

singular values, D:
 [3.41453115 0.91327997] 

right singular vectors, V:
 [[-0.1603542   0.77911004 -0.60603142]
 [-0.1168414  -0.62464247 -0.77212038]] 

UDV-A:
 [[-2.77555756e-17  2.91433544e-16  0.00000000e+00]
 [ 1.22124533e-15  0.00000000e+00  2.22044605e-16]]


In [26]:
# Let's check if the left-singular vectors of A are the eigenvectors of AA^T and if the square root of the non-zero eigenvalues of AA^T are the singular values of A
L,V=np.linalg.eig(np.matmul(A, np.transpose(A)))


print('eighenvectors of AA^T:\n',V,'\n')

print('square root of nonzero eigenvalues of AA^T:\n',np.sqrt(L),'\n')

eighenvectors of AA^T:
 [[-0.98096951  0.19416184]
 [-0.19416184 -0.98096951]] 

square root of nonzero eigenvalues of AA^T:
 [0.91327997 3.41453115] 



In [27]:
# Let's check if the right-singular vectors of A are the eigenvectors of A^TA and square root of the non-zero singular values of A are the eigenvalues of A^TA
L,V=np.linalg.eig(np.matmul(np.transpose(A),A))

#print('eighenvectors of A^TA:\n', np.transpose(V),'\n')
print('eighenvectors of A^TA:\n', V,'\n')

print('square root of nonzero eigenvalues of A^TT:\n',np.sqrt(L),'\n')

eighenvectors of A^TA:
 [[ 0.1603542  -0.9801197   0.1168414 ]
 [-0.77911004 -0.05300318  0.62464247]
 [ 0.60603142  0.19119635  0.77212038]] 

square root of nonzero eigenvalues of A^TT:
 [3.41453115        nan 0.91327997] 



<ipython-input-27-b04f57e20d5b>:7: RuntimeWarning: invalid value encountered in sqrt
  print('square root of nonzero eigenvalues of A^TT:\n',np.sqrt(L),'\n')
